### PR TITLE
refactor - angular example updates

### PR DESCRIPTION
**Pull request by dankreiger**
### Notes:

- I like how you used `ViewChild` to reference the element instead of directly attaching to the DOM selector
- Good call removing the `SCSS` - I agree it's entirely unnecessary for this example (it's just a habit and Angular let's you use it quickly when launching the CLI)
- I like how you used `puppeteer` to make sure the e2e tests work during the CI run
- I'm coming from a React background, so I understand the desire to take advantage of component reusability as opposed to adding in new services 
  - Angular also emphasizes service reusability, but my one problem with Angular is that it offers too much out of the box, and not all these things are needed. In this example where we are rendering a diagram, I understand wanting to have a reusable diagram component with its own logic. Angular purists might argue for using a service here, but I don't think it really matters.

### Changes: 

- removed `diagram.module.ts` and imported the `DiagramComponent` into the `AppModule`
  - I'm not sure why you need a module for the diagram. Maybe in a scaled app, but even then I don't know if it would be absolutely necessary: https://angular.io/guide/architecture-modules
- used `ChangeDetection.OnPush` 
  - this is the optimal way to use components in Angular. You can read more here: https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4  
  - I used `ChangeDetection.OnPush` also on the `App` component, but in larger apps you might not want this - I don't mind removing this from the example
  - you can always trigger change detection manually if need be, but `OnPush` will prevent unnecessary re-renders when things in the DOM change that have nothing to do with the component (React already does this for us).
- used Angular's `HttpClient` instead of the `fetch` API 
  - this client deals with observables rather than promises, so you don't need to watch for changes as the observable will do this for you
  - you also do not have to parse the json responses as the `HttpClient` will prepare this for you
  - `HttpClient` returns an error object, which eases error handling for us
- took advantage of rxjs operators inside of the http request (the retry isn't necessary, but it's nice to have I think - the Angular docs use it in their one of their `HttpClient` examples: https://angular.io/guide/http#retry)

  - here's an example of how the `HttpClient` and `rxjs` are used together in Angular to handle observables, callbacks, and async behavior: https://angular.io/tutorial/toh-pt6#final-code-review

- updated specs accordingly

- also I think it makes for a more interesting example to import the modeler rather than the navigated-viewer since it is interactive. I left a [comment](https://github.com/bpmn-io/bpmn-js-example-angular/compare/master...dankreiger:refactor/angular-example-updates?expand=1#diff-235cb70ee1694e93dc2b75ac7390b2b1R14) but I didn't change anything there 

Hope you find this useful :) If you want to use fetch instead of Angular's HttpClient I understand, but the one thing you really don't need is the diagram.module.ts as far as I can tell

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR.

The basic idea behind the `onChanges` is that the user may change the input `url` to yield loading of a different diagram. I don't see that functionality being present anymore after your refactoring.

The change regards using the Angular `http` service is a good one.

Another shortcoming of this approach is that users are not able to handle errors in upstream components.

How would you handle that in a react-application?

```html
<app-diagram url="foo" onImport="(err, ...) => {

}); />
```

**Comment by nikku** [comment]
Reopened, please give me time to merge the good parts (http, remove module) .

**Comment by nikku** [comment]
Extracted https://github.com/bpmn-io/bpmn-js-example-angular/pull/4#issuecomment-445573395 to https://github.com/bpmn-io/bpmn-js-example-angular/issues/5.

**Comment by nikku** [comment]
> I could also add a select menu if we want and allow the user to change the chart that is imported (but maybe this is too much for a skeleton example)

Definitely too much. We should keep things as simple (and usable) as possible. Hence also the use of the viewer (not the modeler).

**Comment by dankreiger** [comment]
@nikku ok 

- I then added a suggestion for using `ngOnChanges` with `HttpClient`
- If there is an error, I emit an error message upstream and display it in the UI.

I think the current solution with the `fetch` api works too though.

**Comment by nikku** [comment]
Merged your PR, added a few things on top: https://github.com/bpmn-io/bpmn-js-example-angular/pull/7/commits/98844d11dcf8b82d040d068062df38655b827f78

* Change detection is opinionated -> removed it
* Diagram Component is and should be stateless -> testing via emitted events only
* Make importing diagrams work the `rxjs` way (why not, seems like Angular dudes love this thing)

**Comment by dankreiger** [comment]
@dankreiger 👍

**Pull request closed without merging**
