### PR TITLE
Updated to bpmn-js 11.0.1

### PR DESCRIPTION
**Pull request by inventivejon**
Update to newest bpmn-js version to make the example more usefull.

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your contribution. Would be best if you clearly separate bpmn-js updates from other dependency updates.

There seems to be [something wrong on CI](https://github.com/bpmn-io/bpmn-js-example-angular/actions/runs/3584169377/jobs/6185175845#step:6:17). Do your version bumps run locally?

**Comment by inventivejon** [comment]
Hi,
thx for the feedback. Yes, they run locally. I will check the two findings.

BR

**Comment by nikku** [comment]
Any follow-up? If not I'd close this PR and potentially follow up with a bpmn-js only upgrade.

**Comment by inventivejon** [comment]
I will take care of it tomorrow. Thx for the reminder.

**Comment by inventivejon** [comment]
I am not able to separate the general update from the bpmn update. There are too many things depending on each other. I wanted to help, but I guess it is better someone else with more understanding of the dependencies will do it. I will therefore close this PR without finish.

**Comment by nikku** [comment]
Thanks anyway for trying to look into this. We'll see when we get time to update this example.

:+1:

**Pull request closed without merging**
