### PR TITLE
feat(app): Use Promise version of importXML

### LINKED ISSUE #32: Migrate from callbacks to Promises
__Is your feature request related to a problem? Please describe__  

The example app logs a deprecation warning about using the callback version of `importXML`, and refers to the migration guide here: https://github.com/bpmn-io/bpmn-js-callbacks-to-promises

  
__Describe the solution you'd like__

The example app should use the Promise version of `importXML` in a way that conforms to Angular/RxJS conventions.  

__Additional context__

See my take on an implementation here: https://github.com/ParkerM/bpmn-js-example-angular/commit/3af59817f5d9  
I tried replicating the existing behavior, and everything seems to work the same from what I can tell.

I'd be happy to submit a PR, but figured I should open an issue beforehand to invite discussions around the most "correct" way to integrate the new API with Angular/RxJS that respects convention and also accounts for any caveats I may have missed.  
I imagine this is a common use case, so it'd be nice to have a solid vetted recipe for reference.

### PR DESCRIPTION
**Pull request by ParkerM**
__Which issue does this PR address?__

Closes #32 

This migrates usages of the deprecated callback API to the Promise API [per recommendation](https://github.com/bpmn-io/bpmn-js-callbacks-to-promises#importxml).  
This also simplifies RxJS integration via its [`from(Promise) => Observable` operator](https://rxjs-dev.firebaseapp.com/api/index/function/from).

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Thanks for your contribution :clap:

One thing before we merge this, can you maybe squash your commits into one single, so that we keep our history clean?

```text
feat(app): use Promise version of importXML

Closes #32 
```

**Comment by barmac** [comment]
Thanks for your contribution!

**Comment by ParkerM** [comment]
> 
> 
> Thanks for your contribution 👏
> 
> One thing before we merge this, can you maybe squash your commits into one single, so that we keep our history clean?
> 
> ```
> feat(app): use Promise version of importXML
> 
> Closes #32 
> ```

Whoops, sorry just saw this (and thanks for taking care of that for me 😃).  

Re: CI failure, I ran `npm upgrade` and pushed the updated `package-lock.json` which seemed to fix the weird chromedriver errors. The new build error likely comes from [this change](https://github.com/bpmn-io/bpmn-js-example-angular/pull/33/commits/6bffd2d622c349422ce446d5a3babeabc3bb74de#diff-91b719d691b91dd25a516732ea5cdf9668584f3e8f6d38272d8f09f0ad874e97R29) that bumped `@angular-devkit/build-angular` to a version meant for Angular 11. Also note that using `^` over `~` will cause version range issues for that particular package due to its weird versioning scheme.

**Comment by pinussilvestrus** [comment]
Thanks for noticing us @ParkerM! Migrating to Angular@11 might do the trick, right?

**Comment by barmac** [comment]
The update was an outcome of `npm audit fix`. Still, if this may cause some problems, it sounds reasonable to just update to the latest version with `ng`.

**Pull request merged**
